### ISSUE TITLE
Plus maintenu sur github ?

### ISSUE THREAD

**Issue by maccadia** [tranquilit/WAPT-Documentation#4]
Est-ce toujours le dépot de la documentation WAPT ?

Le dernier commit date de 2020 alors que la documentation de la version 2.2 est publiée sur https://www.wapt.fr/en/doc/.

**Comment by unccvince** [comment]
La documentation disponible sur GitHub est celle de WAPT Community.

Tranquil IT arrête la version Community de WAPT et propose maintenant la version Discovery, avec un périmètre iso-fonctionnel par rapport à la version Community.

Discovery est propriétaire et limitée à 300 postes.

L'arrêt du support et des évolutions de WAPT Community explique que la documentation elle-même n'est plus maintenue.
